# Generated by Django 3.2.7 on 2021-09-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_course_model_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_model',
            old_name='course',
            new_name='author',
        ),
    ]
