# Generated by Django 3.2.7 on 2021-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210916_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_model',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
