# Generated by Django 3.2.7 on 2021-09-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_lesson_model_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_model',
            name='title',
        ),
    ]
